# mysql配置
addr: 127.0.0.1:6033
user: root
pass: 1257
charset : utf8
slave_id: 1001 #slave ID
flavor: mysql #mysql or mariadb,默认mysql

#系统相关配置
data_dir: /root/src/golang_working_dir/go-mysql-transfer/logs #应用产生的数据存放地址，包括日志、缓存数据等，默认当前运行目录下store文件夹
logger:
  level: debug #日志级别；支持：debug|info|warn|error，默认info

#目标类型
target: redis # 支持redis、mongodb、elasticsearch、rocketmq、kafka、rabbitmq

#redis连接配置
redis_addrs: 127.0.0.1:6379 #redis地址，多个用逗号分隔
#redis_group_type: cluster   # 集群类型 sentinel或者cluster
#redis_master_name: mymaster # Master节点名称,如果group_type为sentinel则此项不能为空，为cluster此项无效
#redis_pass: 123456 #redis密码
redis_database: 1  #redis数据库 0-16,默认0。如果group_type为cluster此项无效

#规则配置  
rule:
  -
    schema: umail #数据库名称
    table: core_mailbox #表名称
    order_by_column: mailbox_id #排序字段，存量数据同步时不能为空
    column_underscore_to_camel: false #列名称下划线转驼峰,默认为false
    value_encoder: json  #值编码，支持json、kv-commas、v-commas；默认为json；json形如：{"id":123,"name":"wangjie"} 、kv-commas形如：id=123,name="wangjie"、v-commas形如：123,wangjie

    #redis相关
    redis_structure: hash # 数据类型。 支持string、hash、list、set类型(与redis的数据类型一致)，详见使用手册
    redis_key_formatter: "DB:core_mailbox:${DOMAIN}" # KEY格式化表达式，如：${ID}-${USER_NAME},${ID}表示字段id的值、${USER_NAME}表示字段name的值
    redis_key_value: 1 #KEY的值（固定值）；当redis_structure为hash、list、set此值不能为空
    redis_hash_field_column: mailbox #使用哪个列的值作为hash的field，仅redis_structure为hash时起作用，不填写默认使用主键
    
  -
    schema: umail #数据库名称
    table: core_domain_attr #表名称
    order_by_column: id #排序字段，存量数据同步时不能为空
    column_underscore_to_camel: false #列名称下划线转驼峰,默认为false
    value_encoder: json  #值编码，支持json、kv-commas、v-commas；默认为json；json形如：{"id":123,"name":"wangjie"} 、kv-commas形如：id=123,name="wangjie"、v-commas形如：123,wangjie

    #redis相关
    redis_structure: hash # 数据类型。 支持string、hash、list、set类型(与redis的数据类型一致)，详见使用手册
    redis_key_formatter: "DB:core_domain_attr:${DOMAIN_ID}" # KEY格式化表达式，如：${ID}-${USER_NAME},${ID}表示字段id的值、${USER_NAME}表示字段name的值
    redis_key_value: 1 #KEY的值（固定值）；当redis_structure为hash、list、set此值不能为空
    redis_hash_field_column: item #使用哪个列的值作为hash的field，仅redis_structure为hash时起作用，不填写默认使用主键

    
    
    
    